name = "SegyIO"
uuid = "157a0f19-4d44-4de5-a0d0-07e2f0ac4dfa"
authors = ["Henryk Modzelewski <henryk_modzelewski@mac.com>"]
version = "0.7.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = ">= 0.7"
